steps:
  - id: 'install-packages'
    name: 'python'
    waitFor: ['-']
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        pip3 install -r src/requirements.txt

  - id: 'audit-packages'
    name: 'python'
    waitFor: ['install-packages']
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        pip3 install pip-audit
        pip-audit -r src/requirements.txt

  - id: 'run-sonar-scanner'
    name: '${_ARTIFACT_REG}/$PROJECT_ID/docker/sonar-scanner:latest'
    waitFor: ['audit-packages']
    secretEnv: ['SONAR_HOST','SONAR_ORG','SONAR_PROJ','SONAR_TOK']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
        -Dsonar.host.url=$$SONAR_HOST \
        -Dsonar.organization=$$SONAR_ORG \
        -Dsonar.projectKey=$$SONAR_PROJ \
        -Dsonar.login=$$SONAR_TOK \
        -Dsonar.sources=.

  - id: 'run-coverage'
    name: 'python'
    waitFor: ['run-sonar-scanner']
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        cd ./src
        pip3 install -r requirements.txt
        pip3 install coverage
        coverage run test_ut_app.py
        coverage report --omit=test_ut_app.py
        coverage json -o ${_REPO_NAME}_coverage.json
        coverage html -d ${_REPO_NAME}_coverage

  - id: 'copy-coverage-report-to-gcs'
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['run-coverage']
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        cd ./src
        gsutil cp ${_REPO_NAME}_coverage.json gs://${GCS_BUCKET}
        # gsutil cp -r ${_REPO_NAME}_coverage gs://${GCS_BUCKET}

  - id: 'safety-check'
    name: 'python'
    waitFor: ['run-coverage']
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        cd ./src
        pip3 install -r requirements.txt
        pip3 install safety
        safety check

  - id: 'run-test'
    name: 'python'
    waitFor: ['safety-check']
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        cd ./src
        pip3 install -r requirements.txt
        python3 test_ut_app.py

  - id: 'run-snyk'
    name: 'snyk/snyk-cli:python-3.6'
    waitFor: ['run-test']
    secretEnv: ['SNYK_TOK']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip3 install -r src/requirements.txt
        snyk config set api=$$SNYK_TOK
        snyk test --file=src/requirements.txt --package-manager=pip --severity-threshold=medium --json-file-output=${_REPO_NAME}-snyk-report.json
        # snyk code test src --json-file-output=${_REPO_NAME}-code-test-snyk-report.json # un-comment this to throw vulnerability error

  - id: 'copy-snyk-report-to-gcs'
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['run-snyk']
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        gsutil cp ${_REPO_NAME}-snyk-report.json gs://${GCS_BUCKET}
        # gsutil cp ${_REPO_NAME}-code-test-snyk-report.json gs://${GCS_BUCKET}

        # gsutil cp -r ${_REPO_NAME}_coverage gs://${GCS_BUCKET}

substitutions:
    _SERVICE_NAME: 'security-scans'
    _ARTIFACT_REG: 'europe-west2-docker.pkg.dev'
    GCS_BUCKET: 'your_bucket_name'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sonar-host/versions/latest
    env: 'SONAR_HOST'
  - versionName: projects/$PROJECT_ID/secrets/sonar-org/versions/latest
    env: 'SONAR_ORG'
  - versionName: projects/$PROJECT_ID/secrets/sonar-proj/versions/latest
    env: 'SONAR_PROJ'
  - versionName: projects/$PROJECT_ID/secrets/sonar-tok/versions/latest
    env: 'SONAR_TOK'
  - versionName: projects/$PROJECT_ID/secrets/snyk-tok/versions/latest
    env: 'SNYK_TOK'
    
tags: ['${_SERVICE_NAME}','${_REPO_NAME}']
